apiVersion: v1
kind: Service
metadata:
  labels:
    app: jitsi
  name: jvb
spec:
  type: NodePort
  ports:
  - name: udp
    port: 31000
    nodePort: 31000
    protocol: UDP
    targetPort: 31000
  - name: tcp
    port: 31001
    nodePort: 31001
    protocol: TCP
    targetPort: 31001
  selector:
    service: jvb
    app: jvb
